on:
  push:
    branches:
      - develop
      - main

jobs:
  update-preview:
    if: github.ref == 'refs/heads/develop'
    # go on server via ssh and run a bash script for preview environment
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - uses: actions/checkout@v2
      - name: Update Preview
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /home/lfrey/projects/apartifind
            bash update.sh

  update-production:
    if: github.ref == 'refs/heads/main'
    # go on server via ssh and run a bash script for production environment
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Update Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /home/wohnungsmarktberlin/webserver
            bash update.sh
