on:
  push:
    branches:
      - develop

jobs:
  update:
    # go on server via ssh and run a bash script
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - uses: actions/checkout@v2
      - name: Update
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /home/lfrey/projects/apartifind
            bash update.sh
